// constants/places.ts
// ULTRA STABLE DEMO DATABASE (Verified Paths Only)
// All media is mapped to VERIFIED files in PlaceDB.

export const ALL_PLACES = [
  {
    id: "lingaraj-temple",
    title: "Lingaraj Temple",
    slug: "lingaraj-temple",
    category: "Temple",
    description: "Dedicated to Harihara (a unique fusion of Lord Shiva and Lord Vishnu), the Lingaraj Temple is the undisputed crown jewel of Bhubaneswar's ancient architecture. Soaring to a height of 180 feet, this 11th-century masterpiece was built by King Jajati Keshari. The temple complex is vast, containing over 50 smaller shrines enclosed within massive laterite walls. Intricate carvings cover every inch of its towering spire, depicting mythical creatures, gods, and royal processions in astonishing detail. While only Hindus are permitted inside the main sanctum, a viewing platform erected by Lord Curzon allows all visitors to marvel at the sheer scale of the complex. The atmosphere is deeply spiritual, particularly during Shivaratri when thousands gather to witness the lighting of the Mahadipa at the temple's pinnacle. It is a living monument where faith and history intertwine perfectly.",
    description_short: "Experience the spiritual heart of Odisha in this 1,000-year-old architectural giant!",
    location: "Bhubaneswar",
    lat: 20.2381,
    lng: 85.8338,
    avg_duration_mins: 120,
    opening_time: "06:00",
    closing_time: "21:00",
    best_visit_time: "Early Morning",
    rating: 4.8,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/lingaraj-temple1.jpeg"),
    video: require("../PlaceDB/Videos/lingaraj-temple.mp4"),
    gallery: [
        require("../PlaceDB/Images/lingaraj-temple2.jpeg"),
        require("../PlaceDB/Images/lingaraj-temple3.jpeg"),
    ],
  },
  {
    id: "dhauli-shanti-stupa",
    title: "Dhauli Shanti Stupa",
    slug: "dhauli-shanti-stupa",
    category: "Historical",
    description: "Standing stark white against the lush green landscape, the Dhauli Shanti Stupa is a powerful symbol of transformation. It was built on the very hills adjacent to the Daya River, the site of the horrific Kalinga War in 261 BCE. Legend says the river turned red with blood, a sight that filled Emperor Ashoka with such overwhelming remorse that he renounced violence entirely and embraced Buddhism. Built in 1972 by the Japan Buddha Sangha, this brilliant white Peace Pagoda features domed architecture, stone lions, and panels depicting the life of Buddha. Just a short walk below the stupa, visitors can still find Ashoka’s original rock edicts—messages of peace and administration carved into stone over 2,200 years ago. The hilltop also offers a stunning, breezy panoramic view of the surrounding plains.",
    description_short: "The exact hill where a ruthless emperor dropped his sword and found peace.",
    location: "Bhubaneswar",
    lat: 20.1923,
    lng: 85.8396,
    avg_duration_mins: 90,
    opening_time: "06:00",
    closing_time: "18:00",
    best_visit_time: "Sunset",
    rating: 4.6,
    entry_fee: "Free (Parking Paid)",
      image: require("../PlaceDB/Images/dhauli-shanti-stupa1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/dhauli-shanti-stupa2.jpeg"),
        require("../PlaceDB/Images/dhauli-shanti-stupa3.jpeg"),
    ],
      video: require("../PlaceDB/Videos/dhauli-shanti-stupa.mp4"),
  },
  {
    id: "mukteswara-temple",
    title: "Mukteswara Temple",
    slug: "mukteswara-temple",
    category: "Temple",
    description: "Often referred to as the 'Gem of Odia Architecture,' the Mukteswara Temple is a 10th-century marvel that marks a crucial transition point in temple design. Though smaller in scale compared to Lingaraj, it punches far above its weight in exquisite artistry. The defining feature of this temple is its magnificent Torana—an ornate, thickly carved stone archway at the entrance that is unlike anything else in the region. Every inch of the red sandstone is adorned with flawless carvings of smiling damsels, ascetics in meditation, and playful monkeys. The ceiling inside its porch is equally famous, carved in the shape of an eight-petaled lotus. Dedicated to Lord Shiva, the temple sits in a beautifully maintained, quiet garden complex. It is the perfect spot for photography lovers and those who appreciate delicate, world-class stone craftsmanship.",
    description_short: "They call this the 'Gem of Odisha Architecture'—wait until you see the arch!",
    location: "Bhubaneswar",
    lat: 20.2427,
    lng: 85.8425,
    avg_duration_mins: 60,
    opening_time: "06:30",
    closing_time: "19:00",
    best_visit_time: "Golden Hour (Late Afternoon)",
    rating: 4.7,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/mukteswara-temple1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/mukteswara-temple2.jpeg"),
        require("../PlaceDB/Images/mukteswara-temple3.jpeg"),
        require("../PlaceDB/Images/mukteswara-temple4.jpeg"),
        require("../PlaceDB/Images/mukteswara-temple5.jpeg"),
        require("../PlaceDB/Images/mukteswara-temple6.jpeg"),
    ],
      video: require("../PlaceDB/Videos/mukteswara-temple.mp4"),
  },
  {
    id: "rajarani-temple",
    title: "Rajarani Temple",
    slug: "rajarani-temple",
    category: "Temple",
    description: "Rajarani Temple stands out uniquely among Bhubaneswar's heritage sites because it contains no presiding deity inside its sanctum. Built in the 11th century, it is locally known as the 'Love Temple' due to its breathtaking erotic carvings of women and couples, often drawing comparisons to the famous temples of Khajuraho. The temple gets its name not from a king and queen, but from the dull red and yellow sandstone used in its construction, locally called 'Rajarani'. Set amidst a beautifully manicured, expansive green lawn, the temple's spire is decorated with miniature replicas of itself, creating a stunning visual texture. Without the usual crowds of pilgrims, the atmosphere here is incredibly serene, making it a favorite retreat for artists, historians, and tourists looking for a quiet moment of reflection.",
    description_short: "The 'Love Temple' of Odisha where the stones speak the language of romance.",
    location: "Bhubaneswar",
    lat: 20.2415,
    lng: 85.8436,
    avg_duration_mins: 60,
    opening_time: "06:30",
    closing_time: "19:00",
    best_visit_time: "Morning",
    rating: 4.6,
    entry_fee: "Paid (25 Indians / 300 Foreigners)",
    image: require("../PlaceDB/Images/rajarani-temple1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/rajarani-temple2.jpeg"),
        require("../PlaceDB/Images/rajarani-temple3.jpeg"),
        require("../PlaceDB/Images/rajarani-temple4.jpeg"),
        require("../PlaceDB/Images/rajarani-temple5.jpeg"),
    ],
      video: require("../PlaceDB/Videos/rajarani-temple.mp4"),
  },
  {
    id: "bindu-sagar-lake",
    title: "Bindu Sagar Lake",
    slug: "bindu-sagar-lake",
    category: "Spiritual",
    description: "Bindu Sagar, translating to 'Ocean Drop,' is the largest and most sacred water body in Bhubaneswar's Old Town. According to mythology, Lord Shiva created this lake to quench the thirst of Goddess Parvati by bringing drops of water from every holy pool and river across India. Surrounded by dozens of ancient temples—including the towering Lingaraj Temple visible in the background—the lake forms the spiritual center of the city. In the center of the lake sits an island shrine, the Jagati, which hosts the grand Boita Bandana (boat festival) during the winter. It is a stunning place to visit at dusk, as temple bells ring out and locals gather along the stone steps (ghats) for evening rituals and peaceful walks. The reflection of the temple spires on the calm water is a sight to behold.",
    description_short: "A sacred lake holding drops from every holy river in India!",
    location: "Bhubaneswar",
    lat: 20.2405,
    lng: 85.8344,
    avg_duration_mins: 45,
    opening_time: "00:00",
    closing_time: "23:59",
    best_visit_time: "Dusk (Aarti Time)",
    rating: 4.5,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/bindu-sagar-lake1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/bindu-sagar-lake2.jpeg"),
        require("../PlaceDB/Images/bindu-sagar-lake3.jpeg"),
        require("../PlaceDB/Images/bindu-sagar-lake4.jpeg"),
    ],
      video: require("../PlaceDB/Videos/bindu-sagar-lake.mp4"),
  },
  {
    id: "odisha-state-museum",
    title: "Odisha State Museum",
    slug: "odisha-state-museum",
    category: "Historical",
    description: "Established in 1932, the Odisha State Museum is a treasure trove of the state's rich antiquities. Originally housed in Ravenshaw College, Cuttack, it was moved to Bhubaneswar in 1960. The museum boasts an incredible collection spanning multiple galleries including archaeology, epigraphy, numismatics, and armor. Its most prized possession is the vast collection of rare palm-leaf manuscripts, some dating back hundreds of years, detailing ancient science, math, and poetry. Visitors can also marvel at Jain and Buddhist sculptures, traditional musical instruments, and exquisite Patta paintings. It is an essential stop for history buffs and anyone wanting to understand the cultural evolution of the Kalinga empire.",
    description_short: "Dive deep into Odisha's glorious past, from ancient armor to rare palm-leaf manuscripts!",
    location: "Bhubaneswar",
    lat: 20.252,
    lng: 85.842,
    avg_duration_mins: 180,
    opening_time: "10:00",
    closing_time: "17:00",
    best_visit_time: "Afternoon",
    rating: 4.4,
    entry_fee: "Paid (50)",
      image: require("../PlaceDB/Images/odisha-state-museum1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/odisha-state-museum2.jpeg"),
        require("../PlaceDB/Images/odisha-state-museum3.jpeg"),
        require("../PlaceDB/Images/odisha-state-museum4.jpeg"),
    ],
      video: require("../PlaceDB/Videos/odisha-state-museum.mp4"),
  },
  {
    id: "ekamra-kanan",
    title: "Ekamra Kanan Botanical Gardens",
    slug: "ekamra-kanan",
    category: "Nature",
    description: "Spread over 500 acres, Ekamra Kanan is the largest botanical garden and a vital green lung for Bhubaneswar. Maintained by the Regional Plant Resource Centre, the park is a heaven for nature lovers and families seeking a peaceful retreat. It features a stunning glasshouse, a sprawling rose garden, and a massive lake where visitors can enjoy paddle boating. The garden is also deeply committed to conservation, housing a remarkable collection of rare orchids, cacti, and medicinal plants. Whether you are coming for an early morning jog, a family picnic, or simply to birdwatch, the sprawling manicured lawns and shaded forest trails provide a perfect escape from the city hustle.",
    description_short: "Find your zen in the largest botanical paradise of the capital city.",
    location: "Bhubaneswar",
    lat: 20.297,
    lng: 85.816,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "18:00",
    best_visit_time: "Morning",
    rating: 4.4,
    entry_fee: "Paid (25)",
      image: require("../PlaceDB/Images/ekamra-kanan1.jpg"),
      gallery: [
        require("../PlaceDB/Images/ekamra-kanan2.jpg"),
        require("../PlaceDB/Images/ekamra-kanan3.jpg"),
        require("../PlaceDB/Images/ekamra-kanan4.jpg"),
    ],
      video: require("../PlaceDB/Videos/ekamra-kanan.mp4"),
  },
  {
    id: "kala-bhoomi",
    title: "Kala Bhoomi",
    slug: "kala-bhoomi",
    category: "Historical",
    description: "Kala Bhoomi, the Odisha Crafts Museum, is a masterfully designed space that celebrates the incredible craftsmanship and tribal heritage of the state. Unlike traditional enclosed museums, it features laterite stone walls, open-air courtyards, and traditional terracotta tile roofs, replicating a heritage village. The museum is divided into two main zones: the Handicrafts galleries and the Handlooms galleries. Visitors can explore breathtaking displays of Dokra (metal casting), Pattachitra (scroll painting), terracotta art, and the iconic Sambalpuri weaves. Live demonstration zones often feature local artisans at work, and the sprawling courtyard occasionally hosts folk dance performances. It’s a beautifully curated, interactive journey into the soulful artistry of rural Odisha.",
    description_short: "Experience the vibrant heartbeat of Odisha's 62 indigenous tribes all in one place!",
    location: "Bhubaneswar",
    lat: 20.245,
    lng: 85.786,
    avg_duration_mins: 150,
    opening_time: "10:00",
    closing_time: "17:30",
    best_visit_time: "Afternoon",
    rating: 4.8,
    entry_fee: "Paid (50)",
      image: require("../PlaceDB/Images/kala-bhoomi1.jpg"),
      gallery: [
        require("../PlaceDB/Images/kala-bhoomi2.jpg"),
        require("../PlaceDB/Images/kala-bhoomi3.jpg"),
        require("../PlaceDB/Images/kala-bhoomi4.jpg"),
        require("../PlaceDB/Images/kala-bhoomi5.jpg"),
        require("../PlaceDB/Images/kala-bhoomi6.jpg"),
        require("../PlaceDB/Images/kala-bhoomi7.jpg"),
        require("../PlaceDB/Images/kala-bhoomi8.jpg"),
    ],
      video: require("../PlaceDB/Videos/kala-bhoomi.mp4"),
  },
  {
    id: "ram-mandir-bhubaneswar",
    title: "Ram Mandir",
    slug: "ram-mandir-bhubaneswar",
    category: "Temple",
    description: "Located in the bustling heart of the city, Ram Mandir is a magnificent modern temple dedicated to Lord Rama, Goddess Sita, and Lord Lakshmana. Its striking red and white towering spires (shikharas) are visible from miles away, making it one of the most recognizable landmarks in Bhubaneswar. While the city is famous for its ancient Shiva temples, Ram Mandir is a relatively recent addition that has become a major hub of devotion. The temple complex is immaculately clean and features beautifully landscaped gardens. The atmosphere is especially electric during the evening Aarti and on major festivals like Ram Navami and Dussehra, when the temple is gorgeously illuminated and echoes with devotional chants.",
    description_short: "The soaring red and white spires that define the skyline of central Bhubaneswar.",
    location: "Bhubaneswar",
    lat: 20.279,
    lng: 85.841,
    avg_duration_mins: 45,
    opening_time: "06:00",
    closing_time: "21:00",
    best_visit_time: "Evening Aarti",
    rating: 4.7,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/ram-mandir-bhubaneswar1.jpg"),
      gallery: [
        require("../PlaceDB/Images/ram-mandir-bhubaneswar2.jpg"),
        require("../PlaceDB/Images/ram-mandir-bhubaneswar3.jpg"),
        require("../PlaceDB/Images/ram-mandir-bhubaneswar4.jpg"),
    ],
      video: require("../PlaceDB/Videos/ram-mandir-bhubaneswar.mp4"),
  },
  {
    id: "deras-dam",
    title: "Deras Dam",
    slug: "deras-dam",
    category: "Nature",
    description: "Nestled within the lush embrace of the Chandaka-Dampara Elephant Sanctuary, Deras Dam is a breathtaking reservoir that offers a stark contrast to the urban landscape of Bhubaneswar. Originally built for irrigation, it has evolved into one of the most beloved eco-tourism and picnic spots in the region. The dam is surrounded by undulating green hills and dense forests, making it a hotspot for nature photography and birdwatching. A small watchtower provides a stunning panoramic view of the sparkling waters and the surrounding wilderness. While swimming is restricted due to deep waters, taking a guided nature walk along the periphery or simply enjoying a packed lunch with the sound of rustling leaves makes it a rejuvenating escape.",
    description_short: "A hidden oasis wrapped in dense forests, perfect for your weekend getaway.",
    location: "Bhubaneswar",
    lat: 20.364,
    lng: 85.727,
    avg_duration_mins: 180,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Early Morning",
    rating: 4.3,
    entry_fee: "Paid (40)",
      image: require("../PlaceDB/Images/deras-dam1.jpg"),
      gallery: [
        require("../PlaceDB/Images/deras-dam2.jpg"),
        require("../PlaceDB/Images/deras-dam3.jpg"),
        require("../PlaceDB/Images/deras-dam4.jpg"),
    ],
      video: require("../PlaceDB/Videos/deras-dam.mp4"),
  },
  {
    id: "udayagiri-khandagiri-caves",
    title: "Udayagiri & Khandagiri Caves",
    slug: "udayagiri-khandagiri-caves",
    category: "Historical",
    description: "Carved into two facing hills, the Udayagiri (Hill of Sunrise) and Khandagiri (Broken Hill) caves serve as a spectacular testament to ancient Jain history. Commissioned by King Kharavela in the 1st century BCE, these 33 rock-cut caves were designed as residential blocks for Jain monks navigating the monsoon season. The intricate carvings depict royal processions, mythological creatures, and daily life from millennia ago. The most famous, the Hathigumpha (Elephant Cave), features an inscription detailing King Kharavela’s military campaigns. Climbing to the top of Khandagiri offers one of the best panoramic sunset views of modern Bhubaneswar.",
    description_short: "Step back 2,000 years into the rock-cut shelters of ancient monks!",
    location: "Bhubaneswar",
    lat: 20.262543,
    lng: 85.784659,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Sunset (from Khandagiri top)",
    rating: 4.5,
    entry_fee: "Paid (25 Indians / 300 Foreigners)",
      image: require("../PlaceDB/Images/udayagiri-khandagiri-caves1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/udayagiri-khandagiri-caves2.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves3.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves4.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves5.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves6.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves7.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves8.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves9.jpeg"),
        require("../PlaceDB/Images/udayagiri-khandagiri-caves10.jpeg"),
    ],
      video: require("../PlaceDB/Videos/udayagiri-khandagiri-caves.mp4"),
  },
  {
    id: "nandankanan-zoo",
    title: "Nandankanan Zoological Park",
    slug: "nandankanan-zoo",
    category: "Zoo",
    description: "Set amidst the lush Chandaka Forest and built around the serene Kanjia Lake, Nandankanan (meaning 'The Garden of Heaven') is a premier zoological park in India. It is globally renowned for being the host zoo for white tigers and breeding them successfully. Opened to the public in 1960, the zoo spans over 400 hectares and houses over 160 species of animals, reptiles, and birds. Beyond the enclosures, visitors can experience a thrilling lion and tiger safari, wander through India's largest orchid house, or take a peaceful boat ride. It’s an essential biodiversity hotspot bridging conservation and education.",
    description_short: "Meet the majestic White Tigers of Odisha in their natural glory!",
    location: "Bhubaneswar",
    lat: 20.395774,
    lng: 85.825966,
    avg_duration_mins: 240,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Early Morning",
    rating: 4.4,
    entry_fee: "Paid (50)",
    image: require("../PlaceDB/Images/nandankanan-zoo1.jpeg"),
      gallery: [
        require("../PlaceDB/Images/nandankanan-zoo2.jpeg"),
        require("../PlaceDB/Images/nandankanan-zoo3.jpeg"),
        require("../PlaceDB/Images/nandankanan-zoo4.jpeg"),
        require("../PlaceDB/Images/nandankanan-zoo5.jpeg"),
        require("../PlaceDB/Images/nandankanan-zoo6.jpeg"),
        require("../PlaceDB/Images/nandankanan-zoo7.jpeg"),
    ],
      video: require("../PlaceDB/Videos/nandankanan-zoo.mp4"),
  },
  {
    id: "pathani-samanta-planetarium",
    title: "Pathani Samanta Planetarium",
    slug: "pathani-samanta-planetarium",
    category: "Modern",
    description: "Named after the legendary Odia astronomer Pathani Samanta—who famously measured the distance of the sun and stars using simple bamboo instruments—this planetarium is a hub for space enthusiasts. Located near Acharya Vihar, it was established to create awareness about astronomy and the night sky. The main attraction is the domed theater which projects immersive audio-visual shows about the solar system, galaxies, and the mysteries of the universe. The complex also features a well-maintained science park and periodically hosts night-sky viewing sessions using telescopes. It is a fantastic, air-conditioned escape and a highly educational stop, especially for families and students.",
    description_short: "Journey through the cosmos right from the heart of Odisha!",
    location: "Bhubaneswar",
    lat: 20.298182,
    lng: 85.832324,
    avg_duration_mins: 90,
    opening_time: "13:00",
    closing_time: "18:00",
    best_visit_time: "Afternoon (Showtimes)",
    rating: 4.2,
    entry_fee: "Paid (30)",
      image: require("../PlaceDB/Images/pathani-samanta-planetarium1.jpg"),
      gallery: [
        require("../PlaceDB/Images/pathani-samanta-planetarium2.jpg"),
        require("../PlaceDB/Images/pathani-samanta-planetarium3.jpg"),
        require("../PlaceDB/Images/pathani-samanta-planetarium4.jpg"),
        require("../PlaceDB/Images/pathani-samanta-planetarium5.jpg"),
        require("../PlaceDB/Images/pathani-samanta-planetarium6.jpg"),
        require("../PlaceDB/Images/pathani-samanta-planetarium7.jpg"),
        require("../PlaceDB/Images/pathani-samanta-planetarium8.jpg"),
    ],
      video: require("../PlaceDB/Videos/pathani-samanta-planetarium.mp4"),
  },
  {
    id: "kedar-gauri-temple",
    title: "Kedar Gauri Temple",
    slug: "kedar-gauri-temple",
    category: "Temple",
    description: "Kedar Gauri is actually a complex of two separate temples—one dedicated to Lord Shiva (Kedareshwar) and the other to Goddess Parvati (Gauri). Local legend tells a tragic, Romeo-and-Juliet-style story of two lovers, Kedar and Gauri, who sacrificed their lives for each other here; Lord Shiva, moved by their devotion, decreed the spot sacred. The complex is famous for its two holy water tanks (kunds), Khira Kund and Marichi Kund, whose waters are believed to possess miraculous healing properties, particularly for curing ailments and blessing childless couples. Situated close to Mukteswara, it remains a tranquil, heavily shaded sanctuary deeply woven into local folklore.",
    description_short: "A temple of tragic lovers and healing waters hidden in the Old Town.",
    location: "Bhubaneswar",
    lat: 20.242277,
    lng: 85.84022,
    avg_duration_mins: 45,
    opening_time: "06:00",
    closing_time: "20:00",
    best_visit_time: "Morning",
    rating: 4.6,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/kedar-gauri-temple1.jpg"),
      gallery: [
        require("../PlaceDB/Images/kedar-gauri-temple2.jpg"),
        require("../PlaceDB/Images/kedar-gauri-temple3.jpg"),
        require("../PlaceDB/Images/kedar-gauri-temple4.jpg"),
        require("../PlaceDB/Images/kedar-gauri-temple5.jpg"),
    ],
      video: require("../PlaceDB/Videos/kedar-gauri-temple.mp4"),
  },
  {
    id: "jayadev-vatika",
    title: "Jayadev Vatika",
    slug: "jayadev-vatika",
    category: "Nature",
    description: "Named after the illustrious 12th-century Sanskrit poet Jayadeva, who authored the famous Gita Govinda, this vast ecological park spans across 100 acres near the Khandagiri foothills. Jayadev Vatika is designed as a pristine forest retreat rather than a manicured garden. It features winding pathways shaded by dense canopies, making it a favorite for morning walkers, yogis, and picnicking families. The park is uniquely categorized into various thematic sections, including a massive medicinal plant garden that preserves hundreds of rare herbs native to Odisha. With small artificial streams, rustic wooden bridges, and abundant birdlife, it offers a perfect slice of untouched nature right on the edge of the city.",
    description_short: "Lose yourself in miles of shaded trails and rare medicinal gardens.",
    location: "Bhubaneswar",
    lat: 20.2585,
    lng: 85.7725,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Early Morning",
    rating: 4.3,
    entry_fee: "Paid (25)",
      image: require("../PlaceDB/Images/jayadev-vatika1.jpg"),
      gallery: [
        require("../PlaceDB/Images/jayadev-vatika2.jpg"),
        require("../PlaceDB/Images/jayadev-vatika3.jpg"),
    ],
      video: require("../PlaceDB/Videos/jayadev-vatika.mp4"),
  },
  {
    id: "hirakud-dam",
    title: "Hirakud Dam",
    slug: "hirakud-dam",
    category: "Modern",
    description: "Built across the mighty Mahanadi River, the Hirakud Dam is a post-independence engineering marvel and one of the longest earthen dams in the world, stretching over 25 kilometers. Completed in 1957, it created a massive artificial reservoir that looks like a limitless ocean against the horizon. The dam features two observation towers—Gandhi Minar and Nehru Minar—which provide sweeping panoramic views of the water body and the surrounding forested hills. Driving along the dyke road with water on one side and lush greenery on the other is an unforgettable experience. In winter, the vast reservoir becomes a temporary home to thousands of migratory birds, making it a paradise for photographers and nature lovers alike.",
    description_short: "Drive across one of the longest earthen dams in the world!",
    location: "Sambalpur",
    lat: 21.5284,
    lng: 83.8732,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "18:00",
    best_visit_time: "Sunset (from Gandhi Minar)",
    rating: 4.6,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/hirakud-dam1.jpg"),
      gallery: [
        require("../PlaceDB/Images/hirakud-dam2.jpg"),
        require("../PlaceDB/Images/hirakud-dam3.jpg"),
        require("../PlaceDB/Images/hirakud-dam4.jpg"),
        require("../PlaceDB/Images/hirakud-dam5.jpg"),
    ],
      video: require("../PlaceDB/Videos/hirakud-dam.mp4"),
  },
  {
    id: "maa-samaleswari-temple",
    title: "Maa Samaleswari Temple",
    slug: "maa-samaleswari-temple",
    category: "Temple",
    description: "Situated on the banks of the Mahanadi River, the Maa Samaleswari Temple is the spiritual epicenter of Western Odisha. Built in the 16th century by the Chauhan dynasty kings, the temple is dedicated to Goddess Samaleswari, who is revered as the mother of the region. The temple features a unique structural design with a vaulted roof and thick walls that resemble a fort more than a traditional Odisha temple. The main idol is a large block of granite said to be self-manifested (Swayambhu). The temple complex comes alive with incredible energy during the festival of Nuakhai, the premier agricultural festival of the region, where the first grains of the harvest are offered to the Goddess amidst grand celebrations.",
    description_short: "Seek blessings from the presiding mother deity of Western Odisha.",
    location: "Sambalpur",
    lat: 21.473956,
    lng: 83.959087,
    avg_duration_mins: 60,
    opening_time: "06:00",
    closing_time: "20:00",
    best_visit_time: "Morning Aarti",
    rating: 4.7,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/maa-samaleswari-temple1.jpg"),
      gallery: [
        require("../PlaceDB/Images/maa-samaleswari-temple2.jpg"),
        require("../PlaceDB/Images/maa-samaleswari-temple3.jpg"),
    ],
      video: require("../PlaceDB/Videos/maa-samaleswari-temple.mp4"),
  },
  {
    id: "debrigarh-wildlife-sanctuary",
    title: "Debrigarh Wildlife Sanctuary",
    slug: "debrigarh-wildlife-sanctuary",
    category: "Nature",
    description: "Flanking the massive Hirakud Reservoir, Debrigarh Wildlife Sanctuary is a pristine dry deciduous forest that offers one of the best wildlife experiences in Odisha. Because the sanctuary is bordered by water on one side, wild animals frequently come down to the banks to drink, offering spectacular viewing opportunities. It is home to leopards, Indian bison (Gaur), wild boars, sambar deer, and an incredible array of birdlife. Beyond its rich biodiversity, Debrigarh holds significant historical value; it was the base for the legendary freedom fighter Veer Surendra Sai, who used these dense jungles to wage a guerrilla war against the British. The eco-tourism cottages here provide a tranquil stay completely immersed in nature.",
    description_short: "Where the dense jungle meets the backwaters of the Hirakud reservoir.",
    location: "Sambalpur",
    lat: 21.6111,
    lng: 83.6658,
    avg_duration_mins: 240,
    opening_time: "06:00",
    closing_time: "17:00",
    best_visit_time: "Early Morning (Safari)",
    rating: 4.5,
    entry_fee: "Paid (Safari / Entry fees vary)",
      image: require("../PlaceDB/Images/debrigarh-wildlife-sanctuary1.jpg"),
      gallery: [
        require("../PlaceDB/Images/debrigarh-wildlife-sanctuary2.jpg"),
        require("../PlaceDB/Images/debrigarh-wildlife-sanctuary3.jpg"),
        require("../PlaceDB/Images/debrigarh-wildlife-sanctuary4.jpg"),
        require("../PlaceDB/Images/debrigarh-wildlife-sanctuary5.jpg"),
    ],
      video: require("../PlaceDB/Videos/debrigarh-wildlife-sanctuary.mp4"),
  },
  {
    id: "leaning-temple-huma",
    title: "The Leaning Temple of Huma",
    slug: "leaning-temple-huma",
    category: "Temple",
    description: "Located about 23 kilometers from Sambalpur on the rocky banks of the Mahanadi River, the Huma Temple is an architectural anomaly. Dedicated to Lord Bimaleswar (Shiva), the main temple structure leans visibly to one side. Curiously, while the main temple leans in one direction, the smaller boundary walls and nearby shrines lean in the opposite direction. Scientists and historians still debate whether this was a deliberate architectural design to protect it from river currents, or a structural flaw due to earth movements. Another major attraction here is the 'Kudo' fish in the adjacent river. These tame fish are considered sacred; nobody catches them, and tourists enjoy feeding them directly from the temple stairs.",
    description_short: "India's own leaning tower! This Shiva temple defies gravity.",
    location: "Sambalpur",
    lat: 21.2789,
    lng: 83.8152,
    avg_duration_mins: 60,
    opening_time: "06:00",
    closing_time: "18:00",
    best_visit_time: "Afternoon",
    rating: 4.6,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/leaning-temple-huma1.jpg"),
      gallery: [
        require("../PlaceDB/Images/leaning-temple-huma2.jpg"),
        require("../PlaceDB/Images/leaning-temple-huma3.jpg"),
        require("../PlaceDB/Images/leaning-temple-huma4.jpg"),
    ],
      video: require("../PlaceDB/Videos/leaning-temple-huma.mp4"),
  },
  {
    id: "maa-ghanteswari-temple",
    title: "Maa Ghanteswari Temple",
    slug: "maa-ghanteswari-temple",
    category: "Spiritual",
    description: "Approaching the Maa Ghanteswari Temple, you will hear it long before you see it. The entire temple complex, located on the banks of the Mahanadi River, is adorned with thousands of brass bells of all sizes, tied by devotees whose wishes have been fulfilled. Historically, this site served a highly practical purpose: before the Hirakud Dam was built, this area had treacherous whirlpools. The loud ringing of the temple bells in the strong river winds acted as an acoustic lighthouse, warning ancient boatmen of the dangerous waters ahead. Today, it remains a site of deep faith and a visually striking spectacle, where the air is constantly filled with the holy, metallic chimes of gratitude.",
    description_short: "Listen to the symphony of thousands of brass bells swaying in the wind.",
    location: "Sambalpur",
    lat: 21.3536,
    lng: 83.8291,
    avg_duration_mins: 45,
    opening_time: "06:00",
    closing_time: "19:00",
    best_visit_time: "Morning",
    rating: 4.7,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/maa-ghanteswari-temple1.jpg"),
      gallery: [
        require("../PlaceDB/Images/maa-ghanteswari-temple2.jpg"),
        require("../PlaceDB/Images/maa-ghanteswari-temple3.jpg"),
    ],
      video: require("../PlaceDB/Videos/maa-ghanteswari-temple.mp4"),
  },
  {
    id: "cattle-island",
    title: "Cattle Island",
    slug: "cattle-island",
    category: "Nature",
    description: "Before the Hirakud Dam was constructed, this area was a populated village. When the waters rose, villagers relocated but left some cattle behind on a hilltop that turned into an island. Over decades, these domestic cows evolved into larger, wilder, and completely untamed animals. Today, Cattle Island is a captivating natural wonder surrounded by the vast waters of the Hirakud Reservoir. Visitors can take a scenic boat ride from the shore to get a glimpse of this unique ecosystem. The island is densely forested, and the contrast of the blue waters, green canopy, and wild cattle makes it a thrilling eco-tourism destination.",
    description_short: "A submerged hilltop where wild cattle roam free on a secluded island!",
    location: "Sambalpur",
    lat: 21.614,
    lng: 83.791,
    avg_duration_mins: 120,
    opening_time: "06:00",
    closing_time: "17:00",
    best_visit_time: "Morning (Boat ride)",
    rating: 4.4,
    entry_fee: "Paid (Boat hiring)",
      image: require("../PlaceDB/Images/cattle-island1.jpg"),
      gallery: [
        require("../PlaceDB/Images/cattle-island2.jpg"),
        require("../PlaceDB/Images/cattle-island3.jpg"),
    ],
  },
  {
    id: "gudguda-waterfall",
    title: "Gudguda Waterfall",
    slug: "gudguda-waterfall",
    category: "Nature",
    description: "Hidden deep within the Bamra forest division, Gudguda Waterfall is a spectacular three-tiered cascade. The journey to the falls is as magical as the destination, involving a scenic drive through dense forests and vast litchi and mango orchards. Because it is surrounded by hills on three sides, the area remains refreshingly cool even during peak summer. The water carves its way through stepped rock formations, creating natural plunge pools that are perfect for a safe, rejuvenating dip. It is a highly popular picnic spot, but its remote location ensures it retains an untouched, serene charm far from city crowds.",
    description_short: "Trek through lush mango and litchi orchards to find this hidden multi-tiered waterfall.",
    location: "Sambalpur",
    lat: 21.841,
    lng: 84.452,
    avg_duration_mins: 180,
    opening_time: "07:00",
    closing_time: "17:00",
    best_visit_time: "Midday",
    rating: 4.5,
    entry_fee: "Free",
      image: require("../PlaceDB/Images/gudguda-waterfall1.jpg"),
      gallery: [
        require("../PlaceDB/Images/gudguda-waterfall2.jpg"),
    ],
      video: require("../PlaceDB/Videos/gudguda-waterfall.mp4"),
  },
  {
    id: "ushakothi-wildlife-sanctuary",
    title: "Ushakothi Wildlife Sanctuary",
    slug: "ushakothi-wildlife-sanctuary",
    category: "Nature",
    description: "Also known as the Badrama Wildlife Sanctuary, Ushakothi is a haven for raw, unfiltered wilderness. Located about 40 kilometers from Sambalpur, it spans nearly 300 square kilometers of dense dry deciduous forest. The sanctuary is renowned for its significant population of Asian elephants, leopards, panthers, and the elusive flying squirrel. Unlike more commercialized reserves, Ushakothi offers a highly rugged safari experience. Watchtowers strategically placed near watering holes provide excellent vantage points for wildlife photography, especially just after dawn or before dusk when the jungle comes alive with activity and animal calls.",
    description_short: "Embark on an adventure through deep woodlands tracking flying squirrels and wild elephants.",
    location: "Sambalpur",
    lat: 21.564,
    lng: 84.301,
    avg_duration_mins: 180,
    opening_time: "07:00",
    closing_time: "17:00",
    best_visit_time: "Early Morning",
    rating: 4.2,
    entry_fee: "Paid (50)",
      image: require("../PlaceDB/Images/ushakothi-wildlife-sanctuary1.jpg"),
      gallery: [
        require("../PlaceDB/Images/ushakothi-wildlife-sanctuary2.jpg"),
        require("../PlaceDB/Images/ushakothi-wildlife-sanctuary3.jpg"),
        require("../PlaceDB/Images/ushakothi-wildlife-sanctuary4.jpg"),
    ],
      video: require("../PlaceDB/Videos/ushakothi-wildlife-sanctuary.mp4"),
  },
  {
    id: "deer-park-sambalpur",
    title: "Deer Park",
    slug: "deer-park-sambalpur",
    category: "Zoo",
    description: "Situated right in the heart of Sambalpur, the Deer Park is a beautifully maintained, family-friendly enclosure that serves as a quick urban escape. It spans a modest but heavily wooded area and is home to a thriving population of spotted deer (chital), barking deer, and sambar. The park features well-paved walking trails, shaded seating areas, and vibrant flower beds, making it incredibly popular for evening strolls and weekend family outings. Children particularly enjoy watching the herds gather near the fencing during feeding times. It is a quiet, refreshing pocket of nature amidst the bustling city.",
    description_short: "A peaceful green lung in the city where graceful deer roam in the shade.",
    location: "Sambalpur",
    lat: 21.464,
    lng: 83.981,
    avg_duration_mins: 60,
    opening_time: "08:00",
    closing_time: "18:00",
    best_visit_time: "Late Afternoon",
    rating: 4.1,
    entry_fee: "Paid (10)",
      image: require("../PlaceDB/Images/deer-park-sambalpur1.jpg"),
      gallery: [
        require("../PlaceDB/Images/deer-park-sambalpur2.jpg"),
        require("../PlaceDB/Images/deer-park-sambalpur3.jpg"),
        require("../PlaceDB/Images/deer-park-sambalpur4.jpg"),
    ],
      video: require("../PlaceDB/Videos/deer-park-sambalpur.mp4"),
  },
  {
    id: "victoria-memorial-hall",
    title: "Victoria Memorial Hall",
    slug: "victoria-memorial-hall",
    category: "Historical",
    description: "Built in 1904 to commemorate the reign of Queen Victoria, this elegant colonial-era building stands in stark architectural contrast to the ancient temples of Sambalpur. Originally serving as a prominent administrative hub during British rule, the Victoria Memorial Hall is an excellent example of Anglo-Indian brick architecture with high arches and a robust facade. Today, the building serves as a venue for official functions, cultural events, and the Zilla Parishad office. While you cannot always tour the interior, the exterior and the surrounding manicured grounds make it a notable heritage stop for anyone interested in the colonial history of Western Odisha.",
    description_short: "A slice of colonial architecture frozen in time in Western Odisha.",
    location: "Sambalpur",
    lat: 21.465,
    lng: 83.978,
    avg_duration_mins: 45,
    opening_time: "09:00",
    closing_time: "17:00",
    best_visit_time: "Morning",
    rating: 4.3,
    entry_fee: "Free",
  },
  {
    id: "maa-samalei-sarsatia",
    title: "Maa Samalei Sarsatia Dukaan",
    slug: "maa-samalei-sarsatia",
    category: "Modern",
    description: "Sarsatia is not just a sweet; it is a fascinating piece of Sambalpuri culinary heritage. Available strictly in this region, this rare, crispy delicacy resembles a nest of fine golden threads. The secret ingredient? The resin extracted from the twigs of the 'Ganjer' tree found in local forests. The resin is mixed with rice batter and deep-fried into a delicate, mildly sweet web. The process is incredibly labor-intensive and deeply tied to the cultural identity of Western Odisha. Visiting traditional makers like Maa Samalei Sarsatia Dukaan to watch the artisans masterfully swirl the batter into hot oil before tasting a fresh piece is an absolute must-do cultural experience.",
    description_short: "Taste a sweet made from the resin of tree twigs—an exclusive Western Odisha delicacy!",
    location: "Sambalpur",
    lat: 21.467182,
    lng: 83.967434,
    avg_duration_mins: 30,
    opening_time: "07:00",
    closing_time: "16:00",
    best_visit_time: "Morning",
    rating: 4.6,
    entry_fee: "Free (Pay for food)",
      image: require("../PlaceDB/Images/maa-samalei-sarsatia1.jpg"),
      gallery: [
        require("../PlaceDB/Images/maa-samalei-sarsatia2.jpg"),
        require("../PlaceDB/Images/maa-samalei-sarsatia3.jpg"),
    ],
      video: require("../PlaceDB/Videos/maa-samalei-sarsatia.mp4"),
  },
  {
    id: "shree-jagannath-temple",
    title: "Shree Jagannath Temple",
    slug: "shree-jagannath-temple",
    category: "Temple",
    description: "Towering over the coastal town of Puri, the Shree Jagannath Temple is the beating spiritual heart of Odisha. Built in the 12th century by King Anantavarman Chodaganga Deva, this majestic temple is dedicated to Lord Jagannath (a form of Vishnu), along with his siblings Lord Balabhadra and Goddess Subhadra. The temple is world-famous for its annual Rath Yatra (Chariot Festival), where massive wooden chariots are pulled by millions of devotees. The temple's kitchen is reputed to be the largest in the world, cooking Mahaprasad for tens of thousands of people daily in earthen pots using ancient techniques. The profound aura of faith, the soaring 214-foot main spire (Nila Chakra), and the intense devotion of the pilgrims make visiting this Char Dham site a deeply moving experience.",
    description_short: "Experience the divine energy of one of the Char Dham pilgrimage sites of India!",
    location: "Puri",
    lat: 19.804938,
    lng: 85.817939,
    avg_duration_mins: 180,
    opening_time: "05:30",
    closing_time: "22:00",
    best_visit_time: "Early Morning (for Aarti)",
    rating: 4.9,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/jagannath-temple1.jpeg"),
    video: require("../PlaceDB/Videos/jagannath-temple.mp4"),
    gallery: [
        require("../PlaceDB/Images/jagannath-temple2.jpeg"),
        require("../PlaceDB/Images/jagannath-temple3.jpeg"),
        require("../PlaceDB/Images/jagannath-temple4.jpeg"),
    ],
  },
  {
    id: "konark-sun-temple",
    title: "Konark Sun Temple",
    slug: "konark-sun-temple",
    category: "Historical",
    description: "A UNESCO World Heritage site, the Konark Sun Temple is arguably the pinnacle of Odia architecture. Conceived in the 13th century by King Narasimhadeva I as a gigantic stone chariot for the Sun God (Surya), it originally featured a soaring tower that served as a navigational landmark for European sailors, who called it the 'Black Pagoda.' The structure is pulled by seven rearing stone horses and rests on 24 intricately carved wheels that function as exact sundials, capable of telling the time down to the minute. Every inch of the remaining structure is covered in breathtaking stone carvings detailing mythology, exotic animals, and daily life. Even in its ruined state, its massive scale and artistic genius will leave you absolutely spellbound.",
    description_short: "A colossal chariot of stone frozen in time—welcome to the Sun Temple!",
    location: "Konark",
    lat: 19.8876,
    lng: 86.0945,
    avg_duration_mins: 150,
    opening_time: "06:00",
    closing_time: "20:00",
    best_visit_time: "Sunrise",
    rating: 4.8,
    entry_fee: "Paid (40)",
    image: require("../PlaceDB/Images/konark-sun-temple1.jpeg"),
    video: require("../PlaceDB/Videos/konark-sun-temple.mp4"),
    gallery: [
        require("../PlaceDB/Images/konark-sun-temple2.jpeg"),
        require("../PlaceDB/Images/konark-sun-temple3.jpeg"),
        require("../PlaceDB/Images/konark-sun-temple4.jpeg"),
        require("../PlaceDB/Images/konark-sun-temple5.jpeg"),
    ],
  },
  {
    id: "puri-golden-beach",
    title: "Golden Beach",
    slug: "puri-golden-beach",
    category: "Nature",
    description: "Running parallel to the bustling Marine Drive of Puri, the Golden Beach is a spectacular stretch of coastline facing the Bay of Bengal. Recently awarded the prestigious international 'Blue Flag' certification, a dedicated 870-meter stretch of the beach has been transformed into a world-class, eco-friendly zone. It offers impeccable cleanliness, safe swimming zones with trained lifeguards, solar lighting, and modern shower facilities. Beyond the designated Blue Flag area, the wider Puri beach is a hub of activity, featuring famous sand art installations by local artists, bustling evening markets, and camel rides. It is the perfect place to watch fishermen brave the rolling waves at dawn or enjoy a peaceful walk as the sun paints the sky at dusk.",
    description_short: "Pristine sands and crashing waves at one of India’s cleanest Blue Flag beaches!",
    location: "Puri",
    lat: 19.794,
    lng: 85.823,
    avg_duration_mins: 120,
    opening_time: "06:00",
    closing_time: "19:00",
    best_visit_time: "Early Morning / Late Evening",
    rating: 4.7,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/golden-beach-puri1.jpeg"),
    video: require("../PlaceDB/Videos/golden-beach-puri.mp4"),
    gallery: [
        require("../PlaceDB/Images/golden-beach-puri2.jpeg"),
        require("../PlaceDB/Images/golden-beach-puri3.jpeg"),
        require("../PlaceDB/Images/golden-beach-puri4.jpeg"),
        require("../PlaceDB/Images/golden-beach-puri5.jpeg"),
    ],
  },
  {
    id: "chandrabhaga-beach",
    title: "Chandrabhaga Beach",
    slug: "chandrabhaga-beach",
    category: "Nature",
    description: "Located just 3 kilometers from the Sun Temple, Chandrabhaga Beach is steeped in both natural beauty and deep mythology. It is considered one of the finest beaches along the eastern coast of India, offering a starkly different vibe from the busy shores of Puri. The waters here are incredibly clear, and the casuarina trees lining the coast provide a picturesque backdrop. According to legend, the Sun God cured Lord Krishna's son, Samba, of leprosy at this very spot. During the Magha Saptami festival, hundreds of thousands of pilgrims gather here to take a holy dip at dawn and worship the rising sun. For everyday travelers, it is a profoundly peaceful spot, offering arguably the best and most unobstructed sunrise views in the state.",
    description_short: "The most magical sunrise on the eastern coast awaits you here.",
    location: "Konark",
    lat: 19.865989,
    lng: 86.113928,
    avg_duration_mins: 90,
    opening_time: "00:00",
    closing_time: "23:59",
    best_visit_time: "Sunrise",
    rating: 4.6,
    entry_fee: "Free",
  },
  {
    id: "ramachandi-beach",
    title: "Ramachandi Temple & Beach",
    slug: "ramachandi-beach",
    category: "Adventure",
    description: "Ramachandi is a stunning location on the Marine Drive where the Kushabhadra River dramatically empties into the Bay of Bengal. The area gets its name from the ancient Ramachandi Temple hidden gracefully among the casuarina plantations near the river mouth. While the temple draws local devotees, the calm, shallow estuary waters have transformed this spot into Odisha's premier hub for water sports and adventure tourism. Visitors can enjoy jet skiing, speed boating, scuba diving, and paddleboarding in a safe, controlled environment. Every year, it also hosts a massive eco-retreat and surf festival, turning the pristine sands into a vibrant campsite. It is the ultimate fusion of serene nature and high-adrenaline fun.",
    description_short: "Where the river meets the sea—and your jet ski adventure begins!",
    location: "Konark",
    lat: 19.8519,
    lng: 86.0694,
    avg_duration_mins: 180,
    opening_time: "06:00",
    closing_time: "18:00",
    best_visit_time: "Afternoon (for sports)",
    rating: 4.6,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/ramachandi-beach1.jpeg"),
    video: require("../PlaceDB/Videos/ramachandi-beach.mp4"),
    gallery: [
        require("../PlaceDB/Images/ramachandi-beach2.jpeg"),
        require("../PlaceDB/Images/ramachandi-beach3.jpeg"),
    ],
  },
  {
    id: "raghurajpur-heritage-village",
    title: "Raghurajpur Heritage Village",
    slug: "raghurajpur-heritage-village",
    category: "Historical",
    description: "Located amidst groves of coconut, palm, and jackfruit trees, Raghurajpur is a living, breathing museum. It is globally famous as the master center of Pattachitra—the ancient Odia scroll painting dating back to the 12th century. Remarkably, every single family in this village is engaged in traditional arts. Walking through the village feels surreal, as the front walls of the traditional homes are painted with intricate murals depicting mythological tales. Besides Pattachitra, the artisans here also master palm leaf engraving, stone carving, and the Gotipua dance (the precursor to classical Odissi). Visitors can sit with the master craftsmen, watch them create magic with natural colors, and buy world-class art directly from the source.",
    description_short: "Step into a village where every single house is an open-air art gallery!",
    location: "Puri",
    lat: 19.9015,
    lng: 85.8227,
    avg_duration_mins: 120,
    opening_time: "09:00",
    closing_time: "18:00",
    best_visit_time: "Morning",
    rating: 4.8,
    entry_fee: "Free",
  },
  {
    id: "gundicha-temple",
    title: "Gundicha Temple",
    slug: "gundicha-temple",
    category: "Temple",
    description: "Situated at the end of the Grand Road (Bada Danda), exactly 3 kilometers from the main Jagannath Temple, the Gundicha Temple is affectionately known as the 'Garden House of God.' Built with light gray sandstone in the distinct Kalinga architectural style, the temple remains largely empty for most of the year. However, it becomes the center of the universe during the world-famous Rath Yatra. Lord Jagannath, Lord Balabhadra, and Goddess Subhadra travel here on their massive wooden chariots to spend nine days in this beautifully landscaped retreat. Surrounded by lush gardens and thick walls, it offers a deeply peaceful environment compared to the bustling main temple, making it a serene stop for pilgrims.",
    description_short: "Welcome to the beautiful summer garden house of the Lord of the Universe.",
    location: "Puri",
    lat: 19.81654,
    lng: 85.839698,
    avg_duration_mins: 60,
    opening_time: "06:00",
    closing_time: "21:00",
    best_visit_time: "Morning",
    rating: 4.6,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/gundicha-temple1.jpeg"),
    video: require("../PlaceDB/Videos/gundicha-temple.mp4"),
  },
  {
    id: "pipili-applique-village",
    title: "Pipili Applique Village",
    slug: "pipili-applique-village",
    category: "Historical",
    description: "Pipili is a vibrant town on the highway connecting Bhubaneswar to Puri, impossible to miss because of the explosive burst of colors lining its main street. The town is the global center for Odisha's famous appliqué work, known locally as 'Chandua.' This 12th-century craft involves stitching beautifully cut, brightly colored fabrics onto a base cloth to create stunning patterns of flowers, animals, and mythological figures. Originally, this craft was strictly used to make the massive, colorful canopies for the chariots during the Rath Yatra. Today, the master artisans of Pipili create gorgeous lampshades, wall hangings, umbrellas, and bags. It is a visual feast and the absolute best place to pick up an authentic souvenir.",
    description_short: "The most colorful street in Odisha, famous for its brilliant appliqué work!",
    location: "Puri",
    lat: 20.117,
    lng: 85.8284,
    avg_duration_mins: 90,
    opening_time: "09:00",
    closing_time: "20:00",
    best_visit_time: "Late Afternoon",
    rating: 4.4,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/pipili-village1.jpeg"),
    video: require("../PlaceDB/Videos/pipili-village.mp4"),
    gallery: [
        require("../PlaceDB/Images/pipili-village2.jpeg"),
        require("../PlaceDB/Images/pipili-village3.jpeg"),
        require("../PlaceDB/Images/pipili-village4.jpeg"),
    ],
  },
  {
    id: "maa-manikeswari-temple",
    title: "Maa Manikeswari Temple",
    slug: "maa-manikeswari-temple",
    category: "Temple",
    description: "Located in the center of Bhawanipatna, the Maa Manikeswari Temple is the most revered shrine in the Kalahandi district. The presiding deity, Goddess Manikeswari, is a headless deity representing immense power and divine energy. The temple complex is beautifully constructed with traditional red stone, featuring intricate pillars and a peaceful ambiance. It is most famous for the spectacular 'Chatar Jatra' festival held during the Navakhai period. During this grand procession, the deity is brought out, and hundreds of thousands of devotees flood the streets to seek blessings, accompanied by the hypnotic beats of traditional tribal drums like the 'Jena Vadya' and 'Ghumura'. It is a profound immersion into the deep-rooted faith and vibrant culture of Western Odisha.",
    description_short: "Witness the sheer devotion at the spiritual heart of Kalahandi!",
    location: "Bhawanipatna",
    lat: 19.9056,
    lng: 83.1642,
    avg_duration_mins: 45,
    opening_time: "06:00",
    closing_time: "20:00",
    best_visit_time: "Morning (Aarti)",
    rating: 4.7,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/manikeswari-temple1.jpeg"),
    video: require("../PlaceDB/Videos/manikeswari-temple.mp4"),
    gallery: [
        require("../PlaceDB/Images/manikeswari-temple2.jpeg"),
    ],
  },
  {
    id: "phurlijharan-waterfall",
    title: "Phurlijharan Waterfall",
    slug: "phurlijharan-waterfall",
    category: "Nature",
    description: "Situated just 15 kilometers from Bhawanipatna, Phurlijharan is a breathtaking perennial waterfall hidden amidst dense, verdant forests. The Karlapat river plunges from a rocky height of about 30 feet, creating a mesmerizing spectacle. The name 'Phurlijharan' translates to 'flow of small water drops,' perfectly describing the gentle, misty spray that engulfs the surrounding area. The most magical aspect of this waterfall occurs around midday when the sunlight filters through the canopy and hits the fine mist, frequently creating beautiful, vivid rainbows across the base of the falls. With its well-maintained steps, shaded picnic spots, and the constant, soothing roar of the water, it is an absolute paradise for nature lovers and photographers.",
    description_short: "A perennial waterfall where the sunlight dances to create magical rainbows!",
    location: "Bhawanipatna",
    lat: 19.7825,
    lng: 83.1812,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Noon (to see rainbows)",
    rating: 4.4,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/phulrijharan-waterfall1.jpeg"),
    gallery: [
        require("../PlaceDB/Images/phulrijharan-waterfall2.jpeg"),
        require("../PlaceDB/Images/phulrijharan-waterfall3.jpeg"),
    ],
  },
  {
    id: "karlapat-wildlife-sanctuary",
    title: "Karlapat Wildlife Sanctuary",
    slug: "karlapat-wildlife-sanctuary",
    category: "Nature",
    description: "Spanning nearly 175 square kilometers, Karlapat Wildlife Sanctuary is a pristine, deeply forested gem in the Kalahandi district. Dominated by lush Eastern Ghats vegetation, including thick bamboo and sal forests, the sanctuary is a crucial biodiversity hotspot. It is home to a rich variety of wildlife, including leopards, tigers, sambar deer, barking deer, and the elusive Indian wolf. The sanctuary is also incredibly rich in avian life, making it a birdwatcher's delight. Unlike commercialized national parks, Karlapat offers a highly raw and unmanicured wilderness experience. Trekkers can explore its rugged trails, passing through small indigenous tribal villages and numerous hidden streams and minor waterfalls that cut through the dense valleys.",
    description_short: "Venture into the deep, untamed wilderness of the Eastern Ghats!",
    location: "Bhawanipatna",
    lat: 19.642,
    lng: 83.136,
    avg_duration_mins: 240,
    best_visit_time: "Early Morning",
    rating: 4.5,
    entry_fee: "Paid (20)",
    image: require("../PlaceDB/Images/karlapat-wildlife1.jpeg"),
    video: require("../PlaceDB/Videos/karlapat-wildlife.mp4"),
    gallery: [
        require("../PlaceDB/Images/karlapat-wildlife2.jpeg"),
        require("../PlaceDB/Images/karlapat-wildlife3.jpeg"),
    ],
  },
  {
    id: "rabandhar-waterfall",
    title: "Rabandhar Waterfall",
    slug: "rabandhar-waterfall",
    category: "Nature",
    description: "Rabandhar is one of Kalahandi's best-kept secrets. Located about 15 kilometers from Bhawanipatna, this scenic waterfall cascades down a rocky, stepped gorge surrounded by thick deciduous forests. Getting to the base of the falls requires a short, adventurous trek through uneven terrain, making it a thrilling experience for adventure seekers. The water collects in a pristine, natural plunge pool that is incredibly refreshing after the hike. During the monsoon and post-monsoon months, the waterfall swells with energy, roaring through the valley. It remains relatively untouched by commercial tourism, offering visitors a profound sense of isolation and a chance to deeply connect with the raw, unspoiled natural beauty of Western Odisha.",
    description_short: "A stunning, off-the-beaten-path cascade nestled in the rugged hills.",
    location: "Bhawanipatna",
    lat: 19.8242,
    lng: 83.2125,
    avg_duration_mins: 180,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Morning",
    rating: 4.2,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/rabandhara1.jpeg"),
    video: require("../PlaceDB/Videos/rabandhara.mp4"),
    gallery: [
        require("../PlaceDB/Images/rabandhara2.jpeg"),
        require("../PlaceDB/Images/rabandhara3.jpeg"),
        require("../PlaceDB/Images/rabandhara4.jpeg"),
    ],
  },
  {
    id: "asurgarh-fort-ruins",
    title: "Asurgarh Fort Ruins",
    slug: "asurgarh-fort-ruins",
    category: "Historical",
    description: "Asurgarh is one of the most important, yet least explored, archaeological sites in Odisha. Located near Narla in the Kalahandi district, this ancient, fortified settlement dates back over 2,000 years, bridging the Mauryan and Kushan periods. The site features the sprawling remnants of a rectangular fort surrounded by a massive moat, historically fed by the nearby Sandul River. Recent archaeological excavations have unearthed fascinating artifacts, including silver punch-marked coins, terracotta figurines, and beads of semi-precious stones, hinting at a highly advanced and prosperous ancient civilization. Walking through the grassy mounds and ruined earthen ramparts at sunset evokes a deep sense of mystery, offering history enthusiasts a tangible connection to an era long forgotten.",
    description_short: "Walk among the remnants of a 2,000-year-old fortified settlement!",
    location: "Bhawanipatna",
    lat: 19.8821,
    lng: 83.3324,
    avg_duration_mins: 90,
    opening_time: "08:00",
    closing_time: "17:00",
    best_visit_time: "Late Afternoon",
    rating: 4.3,
    entry_fee: "Free",
  },
  {
    id: "dokrichanchara-waterfall",
    title: "Dokrichanchara Waterfall",
    slug: "dokrichanchara-waterfall",
    category: "Nature",
    description: "Dokrichanchara is a spectacular natural and spiritual complex located on the border of the Kalahandi district. The site is famous for its twin waterfalls—Dokridar and Bhairabdar—that plunge dramatically into a deep, rocky gorge. The area is enveloped in stunningly dense greenery and towering cliffs. Beyond the sheer natural beauty, the site holds immense religious significance. The famous Gudahandi caves, known for their ancient prehistoric rock art, are located nearby. The site also features a sacred temple dedicated to Lord Rama, drawing devotees throughout the year. The combination of roaring waterfalls, prehistoric art, ancient shrines, and a sprawling picnic area makes Dokrichanchara an unforgettable, multi-faceted destination for any traveler.",
    description_short: "Twin waterfalls, ancient caves, and a deep gorge—nature's ultimate playground!",
    location: "Bhawanipatna",
    lat: 19.4582,
    lng: 82.8805,
    avg_duration_mins: 180,
    opening_time: "07:00",
    closing_time: "17:00",
    best_visit_time: "Morning",
    rating: 4.6,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/dokrichanchra1.jpeg"),
    video: require("../PlaceDB/Videos/dokrichanchra.mp4"),
  },
];
