// constants/places.ts
// ULTRA STABLE DEMO DATABASE (Verified Paths Only)
// All media is mapped to VERIFIED files in PlaceDB.

export const ALL_PLACES = [
  // --- BHUBANESWAR ---
  {
    id: "lingaraj-temple",
    title: "Lingaraj Temple",
    slug: "lingaraj-temple",
    category: "Temple",
    description: "The crown jewel of Bhubaneswar's ancient architecture. Soaring to 180 feet, this 11th-century masterpiece was built by King Jajati Keshari.",
    location: "Bhubaneswar",
    lat: 20.2381,
    lng: 85.8338,
    avg_duration_mins: 120,
    opening_time: "06:00",
    closing_time: "21:00",
    rating: 4.8,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/Lingraj.jpeg"),
  },
  {
    id: "dhauli-shanti-stupa",
    title: "Dhauli Shanti Stupa",
    slug: "dhauli-shanti-stupa",
    category: "Historical",
    description: "The site of the Kalinga War, now a symbol of peace and Buddhism.",
    location: "Bhubaneswar",
    lat: 20.1923,
    lng: 85.8396,
    avg_duration_mins: 90,
    opening_time: "06:00",
    closing_time: "18:00",
    rating: 4.6,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/Dhauli.jpeg"),
    video: require("../PlaceDB/Videos/Dhauli.mp4"),
    gallery: [
        require("../PlaceDB/Images/Dhauli/Dhauli1.jpeg"),
    ]
  },
  {
    id: "nandankanan-zoo",
    title: "Nandankanan Zoo",
    slug: "nandankanan-zoo",
    category: "Zoo",
    description: "World-famous for its white tiger safari and unique botanical richness.",
    location: "Bhubaneswar",
    lat: 20.3957,
    lng: 85.8259,
    avg_duration_mins: 240,
    opening_time: "08:00",
    closing_time: "17:00",
    rating: 4.4,
    entry_fee: "Paid",
    image: require("../PlaceDB/Images/Nandankanan.jpeg"),
  },
  {
    id: "udayagiri-caves",
    title: "Udayagiri Caves",
    slug: "udayagiri-caves",
    category: "Historical",
    description: "Ancient rock-cut caves built for Jain monks.",
    location: "Bhubaneswar",
    lat: 20.2618,
    lng: 85.7850,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "17:00",
    rating: 4.5,
    entry_fee: "Paid",
    image: require("../PlaceDB/Images/Khandagiri.jpeg"),
  },
  {
    id: "rajarani-temple",
    title: "Rajarani Temple",
    slug: "rajarani-temple",
    category: "Temple",
    description: "An 11th-century temple noted for its ornate carvings and 'Rajarani' sandstone.",
    location: "Bhubaneswar",
    lat: 20.2415,
    lng: 85.8436,
    avg_duration_mins: 60,
    opening_time: "06:30",
    closing_time: "19:00",
    rating: 4.6,
    entry_fee: "Paid",
    image: require("../PlaceDB/Images/Rajarani.jpeg"),
  },

  // --- SAMBALPUR ---
  {
    id: "hirakud-dam",
    title: "Hirakud Dam",
    slug: "hirakud-dam",
    category: "Modern",
    description: "The world's longest earthen dam, built across the Mahanadi River.",
    location: "Sambalpur",
    lat: 21.5284,
    lng: 83.8732,
    avg_duration_mins: 120,
    opening_time: "08:00",
    closing_time: "18:00",
    rating: 4.6,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/Dhauli.jpeg"), // Verified fallback
  },
  {
    id: "maa-samaleswari",
    title: "Maa Samaleswari",
    slug: "maa-samaleswari",
    category: "Temple",
    description: "The presiding deity of Sambalpur.",
    location: "Sambalpur",
    lat: 21.4739,
    lng: 83.959,
    avg_duration_mins: 60,
    opening_time: "06:00",
    closing_time: "20:00",
    rating: 4.7,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/Lingraj.jpeg"),
  },

  // --- PURI & KONARK ---
  {
    id: "pur-jagannath",
    title: "Shree Jagannath Temple",
    slug: "shree-jagannath",
    category: "Temple",
    description: "One of the most sacred pilgrimage sites in India.",
    location: "Puri",
    lat: 19.8049,
    lng: 85.8179,
    avg_duration_mins: 180,
    opening_time: "05:30",
    closing_time: "22:00",
    rating: 4.7,
    entry_fee: "Free",
    image: require("../PlaceDB/Images/Lingraj.jpeg"),
  },
  {
    id: "konark-sun-temple",
    title: "Konark Sun Temple",
    slug: "konark-sun-temple",
    category: "Historical",
    description: "A colossal chariot-shaped UNESCO World Heritage site.",
    location: "Konark",
    lat: 19.8876,
    lng: 86.0945,
    avg_duration_mins: 150,
    opening_time: "06:00",
    closing_time: "20:00",
    rating: 4.8,
    entry_fee: "Paid",
    image: require("../PlaceDB/Images/Rajarani.jpeg"),
  }
];
